import Component from "../welcome-page"

export const metadata = {
  title: "Big Bird Portfolios",
  description: "Generated by create next app",
}

export default function Page() {
  return <Component />
}
